### ISSUE TITLE
Have the latest PRs been released on a docker Hub?

### ISSUE THREAD

**Issue by holyjak** [turnerlabs/turner-defaultbackend#5]
Hi, is there a version after 0.2.0 with the latest changes? Where? I do not see a way to list available versions on quay.io and :latest does not work. Thank you!

**Comment by jritsema** [comment]
I think 0.2.0 effectively had the latest changes but we never pushed the commits to origin.  We also never took the time to setup a CI/CD pipeline for this project since we didn't really envision ongoing changes.

For what it's worth, I just pushed `0.2.1` and `latest` based on the latest code.  Let us know if you need anything else.  Thanks. 

```
docker pull quay.io/turner/turner-defaultbackend:latest
```

**Comment by holyjak** [comment]
Thanks a lot!
